# Generated by Django 2.0.7 on 2018-07-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_added Country and City models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
