# Generated by Django 2.0.7 on 2018-07-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_removed Country model, and changed City model'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='humidity',
            field=models.PositiveIntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='icon_url',
            field=models.URLField(default='weather/images/icons/03d.png'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='pressure',
            field=models.PositiveIntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='temperature',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='weather',
            field=models.CharField(default='sunny', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='weather_description',
            field=models.CharField(default='really sunny', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='wind_direction',
            field=models.CharField(default='NE', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='wind_speed',
            field=models.PositiveIntegerField(default=40),
            preserve_default=False,
        ),
    ]
